# Generated by the cclens release workflow. Do not edit by hand.
class Cclens < Formula
  desc "A lens onto your Claude Code usage"
  homepage "https://github.com/lambdalisue/cclens"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.0/cclens-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "452e167469621852bdc0e56c67473118a7b6c296b3a3d1fa8df3cc3bca13b84f"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.0/cclens-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "11bf188087683696cd5922938db061c16343af24fc6ae9fd68053ad84d3111d1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.0/cclens-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9241f8ac55119e7fc6676d375eec87aafdb89d20393da84e936387b231b2d06e"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.0/cclens-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3e6f1cb07c0eba66606347fc4aa69ad57081a58e0cee5f2d59f040591d23ee20"
    end
  end

  def install
    bin.install "cclens"
  end

  test do
    assert_match "cclens", shell_output("#{bin}/cclens --help")
  end
end
