# Generated by the cclens release workflow. Do not edit by hand.
class Cclens < Formula
  desc "A lens onto your Claude Code usage"
  homepage "https://github.com/lambdalisue/cclens"
  version "0.2.2"

  on_macos do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.2.2/cclens-v0.2.2-aarch64-apple-darwin.tar.gz"
      sha256 "9ea14d135bd452a1c39c30b3ea7023d59fb38e4918edc78b8364b91fbba83fdb"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.2.2/cclens-v0.2.2-x86_64-apple-darwin.tar.gz"
      sha256 "2f04fc3a87cb9ef94a4cccc56e2d5ff96796b27737b490acf01d00130294f6de"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.2.2/cclens-v0.2.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "86ed02a90430ab2697d0b11d95e7cc9e2fa0f617e3dc95dda5e4bfea7a8d60df"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.2.2/cclens-v0.2.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e59eca34a03b7027518fe0e4d901d89fa1679abf65636650f13aaaf3ef968dfc"
    end
  end

  def install
    bin.install "cclens"
  end

  test do
    assert_match "cclens", shell_output("#{bin}/cclens --help")
  end
end
