# Generated by the cclens release workflow. Do not edit by hand.
class Cclens < Formula
  desc "A lens onto your Claude Code usage"
  homepage "https://github.com/lambdalisue/cclens"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.1/cclens-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "d7b1b5296384f8242162963dfcaa5e0f52f9f0257d767691f04bada8f94a833e"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.1/cclens-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "b1f971dd567f7c7852277f0fb05a95803531a860a400d859c19cc6e83b3d0231"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.1/cclens-v0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "724b14440984dbcb2c644097a7e72bd2ae74a504c07fe5687e525c028dc2464c"
    end
    on_intel do
      url "https://github.com/lambdalisue/cclens/releases/download/v0.1.1/cclens-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e01b440ec590059bd617be6d2b9750cb48e6b1f15eaa15245895bc5a0ddc340c"
    end
  end

  def install
    bin.install "cclens"
  end

  test do
    assert_match "cclens", shell_output("#{bin}/cclens --help")
  end
end
